# --- CONFIG BÁSICA ---
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

FPS = 60

TILE_SIZE = 32

SCROLL_THRESH = 150

PLAYER_SCALE = 2

SCORES_FILE = "scores_escapa.txt"

WORLD_W = 35
WORLD_H = 25

# --- ANIMACIONES JUGADOR ---
ANIM_IDLE = 0
ANIM_RUN_UP = 1
ANIM_RUN_DOWN = 2
ANIM_RUN_LEFT = 3
ANIM_RUN_RIGHT = 4

# --- ANIMACIONES ENEMIGO ---
ENEMY_IDLE = 0
ENEMY_RUN_UP = 1
ENEMY_RUN_DOWN = 2
ENEMY_RUN_LEFT = 3
ENEMY_RUN_RIGHT = 4

# --- ENEMIGOS ---
ENEMY_SPEED = 80                     
ENEMY_VISION_RADIUS = 3 * TILE_SIZE  
PATROL_RADIUS_TILES = 3            
ANIM_COOLDOWN = 150    

DAMAGE_COOLDOWN = 1.2

NUM_ENEMIES = 6

# --- VIDA (CORAZONES) ---
HEART_SIZE = 32

HEART_COUNT = 3        
HEART_HP = 2          
MAX_HEALTH = HEART_COUNT * HEART_HP    # 6

 
# --- ENERGÍA ---

ENERGY_FRAMES = 9
MAX_ENERGY = ENERGY_FRAMES - 1 
ENERGY_SIZE = 48

# --- SPRINT
SPRINT_MULT = 1.5           
ENERGY_DRAIN_PER_SEC = 3.0  
ENERGY_REGEN_PER_SEC = 0.9  

SPRINT_LOCK_TIME = 2.5

# --- TRAMPAS ---
MAX_TRAPS = 3
TRAP_COOLDOWN = 5.0      
ENEMY_RESPAWN_TIME = 10.0

# --- PUNTAJE ---
SCORE_TRAP_KILL = 50        
SCORE_TIME_FACTOR = 1000    
SCORE_TRAP_USED_PENALTY = 5

# ---------- MODO CAZADOR ----------

CAZADOR_KILL_SCORE = 50      
CAZADOR_EXIT_PENALTY = 30    
CAZADOR_TIME_LIMIT = 30
TIME_LIMIT = 30.0